import type { Metadata } from "next";
import { Aclonica } from "next/font/google";
import "./globals.css";

const aclonica = Aclonica({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-aclonica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        style={{ "--font-satoshi": "Satoshi" } as React.CSSProperties}
        className={`${aclonica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}